version: '3.1'
services:

  hello-world:
    image: com.ralph.microprofile/hello-world
    environment:
      # Payara-Micor ENV
      MP_OPENAPI_SERVERS: "http://superlocal:8888,http://localhost:8080"
    ports:
      - "8080:8080"
 



