{
 "title": "My Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "base_cpu_availableProcessors" }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(base_cpu_systemLoadAverage)",
     "legendFormat": "{{instance}} {{area}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum (base_cpu_processCpuLoad)", "legendFormat": "{{instance}} {{area}}" }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (base_memory_usedHeap_bytes)",
     "legendFormat": "{{instance}} {{area}}"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "GET Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(application_data_total{method=\"load\"}[1m])",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "PUT Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(application_data_total{method=\"save\"}[1m])",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}