version: '3.1'
services:

  microservice:
    image: com.ralph.microprofile/hello-world
    environment:
      # Payara-Micor ENV
      MP_OPENAPI_SERVERS: "http://superlocal:8888,http://localhost:8080"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
 
    
  prometheus:
    image: prom/prometheus:v2.30.4
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
      - prometheusdata:/prometheus/

  
  grafana:
    image: grafana/grafana:latest
    ports: 
      - "3000:3000" 


volumes:
  prometheusdata:
